version: '3'

services:

    mongodb:
        image: mongo
        container_name: mongodb-api
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=example

    mongo-express:
        image: mongo-express
        container_name: mongo-express-api
        ports:
            - "8081:8081"
        environment:
            - ME_CONFIG_MONGODB_SERVER=mongodb
            - ME_CONFIG_MONGODB_ADMINUSERNAME=root
            - ME_CONFIG_MONGODB_ADMINPASSWORD=example
            - ME_CONFIG_BASICAUTH_USERNAME=estatcamp
            - ME_CONFIG_BASICAUTH_PASSWORD=estatcamp
        depends_on:
            - mongodb

    api:
        build: .
        container_name: api
        command: npm start
        restart: on-failure
        environment:
            - MONGODB_URI=mongodb://root:example@mongodb-api:27017/
        ports:
            - "4000:4000"
        depends_on:
            - mongo-express